------------------------------------
-- Define table
------------------------------------

BEGIN;

DROP TABLE IF EXISTS ascendco.analytic_productivity;

CREATE TABLE IF NOT EXISTS ascendco.analytic_productivity (
        id                    uuid               NOT NULL DEFAULT NULL,
        data_file_id          uuid               NOT NULL DEFAULT NULL,
        hsys_id               uuid               NOT NULL DEFAULT NULL,
        facility_id           uuid               NOT NULL DEFAULT NULL,
        facility_location_id  uuid               NOT NULL DEFAULT NULL,
        specialty_id          uuid               NOT NULL DEFAULT NULL,
        item_type_id          uuid               NOT NULL DEFAULT NULL,
        inv_id                uuid               NOT NULL DEFAULT NULL,
        item_id               uuid               NOT NULL DEFAULT NULL,

        start_utc             timestamptz        NOT NULL DEFAULT '-infinity',
        start_local           timestamptz        NOT NULL DEFAULT '-infinity',
        end_utc               timestamptz        NOT NULL DEFAULT '-infinity',
        end_local             timestamptz        NOT NULL DEFAULT '-infinity',

        points_per_hour       double precision   NOT NULL DEFAULT '0',
        assembly_hour         double precision   NOT NULL DEFAULT '0',
        pause_hour            double precision   NOT NULL DEFAULT '0',

        num_inst              integer            NOT NULL DEFAULT 0,
        assembly_minutes      integer            NOT NULL DEFAULT 0,
        pause_minutes         integer            NOT NULL DEFAULT 0,
        points                integer            NOT NULL DEFAULT 0,
        pg_con_id             integer            GENERATED BY DEFAULT AS IDENTITY UNIQUE,
        marked_for_deletion   boolean            NOT NULL DEFAULT FALSE,

        user_name             citext             NOT NULL DEFAULT NULL,
        inv_name              citext             NOT NULL DEFAULT NULL,
        item_name             citext             NOT NULL DEFAULT NULL,
        tray_or_pack          citext             NOT NULL DEFAULT NULL
);
ALTER TABLE ascendco.analytic_productivity
    ADD CONSTRAINT analytic_productivity_id_pkey PRIMARY KEY (id);

ALTER TABLE ascendco.analytic_productivity OWNER TO user_change_structure;
COMMIT;

------------------------------------
-- Build indexes
------------------------------------
CREATE INDEX analytic_productivity_facility_id_ix_fkey ON ascendco.analytic_productivity (facility_id);

CREATE INDEX analytic_productivity_hsys_id_ix_fkey ON ascendco.analytic_productivity (hsys_id);

CREATE INDEX analytic_productivity_item_type_id_ix_fkey ON ascendco.analytic_productivity (item_type_id);

CREATE INDEX analytic_productivity_marked_for_deletion_ix_bgin ON ascendco.analytic_productivity
USING GIN (marked_for_deletion)
WHERE
    marked_for_deletion = TRUE;

------------------------------------
-- Add triggers
------------------------------------
CREATE TRIGGER trigger_analytic_productivity_after_delete
    AFTER DELETE
    ON ascendco.analytic_productivity
	REFERENCING OLD TABLE AS deleted_rows
    FOR EACH STATEMENT
    EXECUTE PROCEDURE ascendco.trigger_function_log_deletion_count ();

CREATE TRIGGER trigger_analytic_productivity_before_truncate
    BEFORE TRUNCATE
    ON ascendco.analytic_productivity
    FOR EACH STATEMENT
    EXECUTE PROCEDURE ascendco.trigger_function_log_truncation_count ();