CREATE OR REPLACE PROCEDURE ascendco.system_delete_marked_and_log_sp ()
AS $BODY$

BEGIN

-- Execute configured auto-deletes and save results in a CTE.
with deletion_results as (
    SELECT *
      FROM system_delete_marked()
    )

-- Take the results from the CTE where something actually got deleted and push them into deletion_log.
INSERT INTO deletion_log (
                  schema_name,
                  table_name,
                  operation_name,
                  deleted_count)

         SELECT  schema,
                 table_name,
                 'DELETE',
                 count

            FROM deletion_results

           WHERE count > 0;

-- ANALYZE modified tables.
-- Note: We're in a stored procedure, there is no result returned. Use PERFORM on this function instead of SELECT.
PERFORM system_analyze_after_deletions();

END;

$BODY$
	LANGUAGE plpgsql;


COMMENT ON PROCEDURE ascendco.system_delete_marked_and_log_sp() IS '
/*
The system_delete_marked stored procedure is generated by PgBuild_ClearDeletedRecords to include
hard-coded references to tables where we do auto-cleanup.

Leviathan periodically calls system_delete_marked_and_log_sp, this routine,
to run whatever deletes are configured in system_delete_marked_and_log_sp.
You can see this in the deletion_results CTE at the top of this function.
The summaries of those deletions are then intserted into deltion_log in the main body of this function.

Note: This is a stored PROCEDURE and is invoked with CALL, not SELECT.
*/
';

ALTER PROCEDURE ascendco.system_delete_marked_and_log_sp()
	OWNER TO user_bender;
